###***add in args here and update to version 3 if it's possible with nvidia runtime

version: '2.1'
services:
    redis:
        image: "redis:latest"
        container_name: "redis"
        hostname: "redis"
        restart: always
        networks:
            - crackq_net
        ports:
            - "127.0.0.1:6379:6379"
        #volumes:
        #    - /var/crackq/:/var/crackq
    crackq:
        image: "opencl-crackq"
        ports:
                - "127.0.0.1:8080:8080"
        depends_on:
                - redis
        networks:
            - crackq_net
        container_name: "crackq"
        hostname: "crackq"
        volumes:
            - /var/crackq/:/var/crackq
            - ./crackq:/opt/crackq/build/crackq/
        stdin_open: true
        user: crackq
        tty: true
        environment:
                PYTHONPATH: "/opt/crackq/build/"
                MAIL_USERNAME: ${MAIL_USERNAME}
                MAIL_PASSWORD: ${MAIL_PASSWORD}
        command:
                #sh -c "/bin/bash"
                sh -c "pip3 install -e . --user && cd ./crackq
                && python3 -c 'from crackq import hash_modes; hash_modes.HModes.update_modes()'
                && /usr/local/bin/circusd /opt/crackq/build/circus.ini"
    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        image: "nginx-crackq"
        restart: always
        depends_on:
                - crackq 
        container_name: "nginx"
        hostname: "nginx"
        cap_add:
                - NET_ADMIN      
        ports:
             - "443:443"
        volumes:
             - /var/crackq/logs/nginx/:/var/log/nginx/
             - /var/crackq/files/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - crackq_net

networks:
    crackq_net:
