FROM nginx:1.16.1

RUN rm /etc/nginx/nginx.conf
COPY cfg/nginx.conf /etc/nginx/
RUN mkdir /var/www/
RUN mkdir /var/www/static/
COPY dist/ /var/www/static/
RUN chown -R nginx:nginx /var/www/
RUN chmod -R 755 /var/www/static/
#COPY /var/crackq/files/nginx/nginx.conf /etc/nginx/
#COPY /var/crackq/files/nginx/conf.d/* /etc/nginx/conf.d/
#RUN chown nginx:nginx /etc/nginx/nginx.conf
RUN rm /etc/nginx/conf.d/default.conf
#COPY cfg/crackq_nginx.conf /etc/nginx/conf.d/

